module.exports.endpoints = {
    // user auth
    follow: "api/user/follow",
    delete: "api/user/delete",
    signin: "api/user/signin",
    signup: "api/user/register",
    otpsend: "api/user/otpsend",
    unfollow: "api/user/unfollow",
    otpverify: "api/user/verifyotp",
    reportuser: "api/user/reportuser",
    unfriend: "api/user/removefriend",
    acceptfriend: "api/user/acceptfriend",
    removefriend: "api/user/removefriend",
    updateStatus: "api/user/updateStatus",
    getSingleUser: "api/user/getSingleUser",
    updateprofile: "api/user/updateprofile",
    passwordchange: "api/user/passwordchange",
    signupWithImage: "api/user/registerWithImage",

    // posts
    getall: "api/post",
    like: "api/post/like",
    createpost: "api/post",
    reply: "api/post/reply",
    saved: "api/post/saved",
    recent: "api/post/recent",
    unlike: "api/post/unlike",
    comment: "api/post/comment",
    mytopics: "api/post/mytopics",
    editpost: "api/post/editpost",
    myanswers: "api/post/myanswers",
    editreply: "api/post/editreply",
    addtosave: "api/post/addtosave",
    deletepost: "api/post/deletepost",
    singlepost: "api/post/singlepost",
    deletereply: "api/post/deletereply",
    editcomment: "api/post/editcomment",
    othertopics: "api/post/othertopics",
    otheranswers: "api/post/otheranswers",
    deletecomment: "api/post/deletecomment",
    removefromsave: "api/post/removefromsave",
}